services:
    mysql:
        image: mysql:8.4
        container_name: kbdb_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: kimbledb
            # MYSQL_USER: ${DB_USER}
            # MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
    mysql_data:
